##
## change this params for your model
##

# directory for all model sources
MODEL_DIR=sample_src

# main model file
MODEL_FILE=$(MODEL_DIR)/sample.py

# model configuration file
MODEL_CFG=$(MODEL_DIR)/config.json
